name: Refresh TIM cache

on:
  push:
    branches:
      - main

jobs:
  make-curl-request:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Curl Call
        run: curl -X GET https://tim.jyu.fi/cs/refresh
